// starters
export const starters = [
  {
    addedBy: "Ferris Osteria",
    description: "Fresh mozzarella with tomatoes and basil",
    email: "contact@ferrisosteria.com",
    foodCategory: "Starters",
    foodName: "Mozzarella Pomodori e Basilico",
    img: "https://i.ibb.co/PvnXmjg6/Veal.jpg", // Updated image URL
    origin: "Italy",
    price: "12.10",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Mixed vegetarian appetizer platter",
    email: "contact@ferrisosteria.com",
    foodCategory: "Starters",
    foodName: "Antipasto Misto Vegetare",
    img: "https://i.ibb.co/PvnXmjg6/Veal.jpg", // Updated image URL
    origin: "Italy",
    price: "12.50",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Mushrooms filled with spinach and Gorgonzola sauce, baked with cheese",
    email: "contact@ferrisosteria.com",
    foodCategory: "Starters",
    foodName: "Funghi Gorgonzola",
    img: "https://i.ibb.co/PvnXmjg6/Veal.jpg", // Updated image URL
    origin: "Italy",
    price: "11.80",
    quantity: "45",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Honeydew melon with smoked beef",
    email: "contact@ferrisosteria.com",
    foodCategory: "Starters",
    foodName: "Melone con Bresaola",
    img: "https://i.ibb.co/PvnXmjg6/Veal.jpg", // Updated image URL
    origin: "Italy",
    price: "16.20",
    quantity: "30",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Thinly sliced veal in tuna sauce with capers and lemon",
    email: "contact@ferrisosteria.com",
    foodCategory: "Starters",
    foodName: "Vitello Tonnato",
    img: "https://i.ibb.co/PvnXmjg6/Veal.jpg", // Updated image URL
    origin: "Italy",
    price: "14.30",
    quantity: "35",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Salmon carpaccio with red pepper and lemon sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Starters",
    foodName: "Carpaccio di Salmone",
    img: "https://i.ibb.co/PvnXmjg6/Veal.jpg", // Updated image URL
    origin: "Italy",
    price: "14.10",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Beef carpaccio with arugula and shaved Parmesan, served with a special sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Starters",
    foodName: "Carpaccio di Manzo",
    img: "https://i.ibb.co/PvnXmjg6/Veal.jpg", // Updated image URL
    origin: "Italy",
    price: "14.10",
    quantity: "35",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Seafood salad",
    email: "contact@ferrisosteria.com",
    foodCategory: "Starters",
    foodName: "Insalata con Frutti di Mare",
    img: "https://i.ibb.co/PvnXmjg6/Veal.jpg", // Updated image URL
    origin: "Italy",
    price: "13.90",
    quantity: "45",
  },
];
export const soup_salad = [
    {
      addedBy: "Ferris Osteria",
      description: "Tomato cream soup",
      email: "contact@ferrisosteria.com",
      foodCategory: "Soups",
      foodName: "Tomato Soup",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "5.50",
      quantity: "50",
    },
    {
      addedBy: "Ferris Osteria",
      description: "Fresh vegetable soup",
      email: "contact@ferrisosteria.com",
      foodCategory: "Soups",
      foodName: "Vegetable Soup",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "6.00",
      quantity: "50",
    },
    {
      addedBy: "Ferris Osteria",
      description: "Onion soup",
      email: "contact@ferrisosteria.com",
      foodCategory: "Soups",
      foodName: "Onion Soup",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "6.50",
      quantity: "40",
    },
    {
      addedBy: "Ferris Osteria",
      description: "Fish soup with various fish and vegetable strips",
      email: "contact@ferrisosteria.com",
      foodCategory: "Soups",
      foodName: "Fish Soup",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "12.50",
      quantity: "35",
    },
    {
      addedBy: "Ferris Osteria",
      description: "Salad with fresh sheep's cheese and homemade dressing",
      email: "contact@ferrisosteria.com",
      foodCategory: "Salads",
      foodName: "Pecorino Salad",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "10.30",
      quantity: "40",
    },
    {
      addedBy: "Ferris Osteria",
      description: "Large mixed salad with homemade dressing",
      email: "contact@ferrisosteria.com",
      foodCategory: "Salads",
      foodName: "Mixed Salad",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "9.50",
      quantity: "45",
    },
    {
      addedBy: "Ferris Osteria",
      description: "Large mixed salad with tuna",
      email: "contact@ferrisosteria.com",
      foodCategory: "Salads",
      foodName: "Tuna Salad",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "12.50",
      quantity: "35",
    },
    {
      addedBy: "Ferris Osteria",
      description: "Arugula salad with cherry tomatoes and freshly grated Parmesan",
      email: "contact@ferrisosteria.com",
      foodCategory: "Salads",
      foodName: "Arugula Salad",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "13.50",
      quantity: "40",
    },
    {
      addedBy: "Ferris Osteria",
      description: "Large mixed salad with rosemary, carrots, chicken breast strips, and cherry tomatoes",
      email: "contact@ferrisosteria.com",
      foodCategory: "Salads",
      foodName: "Chicken Salad",
      img: "https://i.ibb.co.com/4g0smGYM/Carpaccio.jpg",
      origin: "Italy",
      price: "13.50",
      quantity: "40",
    }
  ]

//-------------------- Pasta -----------------------------
export const fresh_pasta = [
  {
    addedBy: "Ferris Osteria",
    description:
      "Fresh pasta with sautéed porcini mushrooms and beef fillet tips, drizzled with truffle oil",
    email: "contact@ferrisosteria.com",
    foodCategory: "Fresh Pasta",
    foodName: "Casereccie",
    img: "https://i.ibb.co/W4rZ05Q1/slide-8.webp", // Updated image URL
    origin: "Italy",
    price: "14.50",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Fresh egg pasta with a fruity tomato sauce and tender mozzarella cubes",
    email: "contact@ferrisosteria.com",
    foodCategory: "Fresh Pasta",
    foodName: "Finferli Caprese",
    img: "https://i.ibb.co/W4rZ05Q1/slide-8.webp", // Updated image URL
    origin: "Italy",
    price: "11.50",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Gnocchi filled with spinach and ricotta, served with turkey breast strips in a light tomato sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Fresh Pasta",
    foodName: "Gnocchi Ripieni",
    img: "https://i.ibb.co/W4rZ05Q1/slide-8.webp", // Updated image URL
    origin: "Italy",
    price: "12.40",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Fine ribbon pasta with chicken breast strips and fresh mushrooms in cream sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Fresh Pasta",
    foodName: "Taglioni al Pollo",
    img: "https://i.ibb.co/W4rZ05Q1/slide-8.webp", // Updated image URL
    origin: "Italy",
    price: "14.40",
    quantity: "45",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Black ribbon pasta with salmon strips and shrimp in a delicate lobster cream sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Fresh Pasta",
    foodName: "Tagliatelle alla Verone",
    img: "https://i.ibb.co/W4rZ05Q1/slide-8.webp", // Updated image URL
    origin: "Italy",
    price: "16.50",
    quantity: "35",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Ribbon pasta with beef fillet tips, fresh mushrooms in a spicy cream sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Fresh Pasta",
    foodName: "Tagliatelle dello Chef",
    img: "https://i.ibb.co/W4rZ05Q1/slide-8.webp", // Updated image URL
    origin: "Italy",
    price: "13.30",
    quantity: "40",
  },
];

const classic_pasta = [
  {
    addedBy: "Ferris Osteria",
    description: "Spaghetti with ham in cream sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Spaghetti Carbonara",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "9.60",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Spaghetti with shrimp, red pepper in lobster sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Spaghetti Pavarotti",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "10.70",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Spaghetti with garlic and olive oil",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Spaghetti Aglio e Olio",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "8.50",
    quantity: "55",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Spaghetti with beef fillet tips, fresh mushrooms in a delicate cream sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Spaghetti Don Ferris",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "11.90",
    quantity: "45",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Penne with olives and garlic in a spicy tomato sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Penne Arrabiata",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "11.90",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Penne pasta in Gorgonzola sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Penne Gorgonzola",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "9.50",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Penne with beef fillet tips, fresh mushrooms in a delicate cream sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Penne Mammamia",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "11.30",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Tagliatelle with sun-dried tomatoes, arugula, garlic, and grated sheep cheese",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Tagliatelle Verde",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "10.00",
    quantity: "35",
  },
  {
    addedBy: "Ferris Osteria",
    description:
      "Tagliatelle with salmon, zucchini, pink cream sauce, and lobster sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Tagliatelle Salmone",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "13.80",
    quantity: "30",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Stuffed pasta with ham in cream sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Tortellini alla Panna",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "9.70",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Stuffed pasta with cheese filling in Gorgonzola sauce",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Tortellini Gorgonzola",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "10.80",
    quantity: "45",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Homemade baked pasta gratinated with cheese",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Lasagne al Forno (Minced Meat)",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "11.50",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Homemade baked pasta gratinated with cheese",
    email: "contact@ferrisosteria.com",
    foodCategory: "Classic Pasta",
    foodName: "Lasagne al Forno (Salmon)",
    img: "https://i.ibb.co.com/Wvzssyxd/10.png",
    origin: "Italy",
    price: "11.80",
    quantity: "50",
  },
];

const pizza = [
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with salami",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Salami",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "9.90",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with arugula and grated Parmesan",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Verde",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "9.00",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with ham and pineapple",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Hawaii",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "10.00",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with tuna and onions",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Tonno",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "10.50",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with fresh mushrooms, salami, ham, and pepperoni",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Capricciosa",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "10.60",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with smoked beef",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Bresaola",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "13.50",
    quantity: "35",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with four different cheeses",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Quattro Formaggi",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "11.40",
    quantity: "35",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with mozzarella, tomatoes, basil",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Mozzarella",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "11.30",
    quantity: "35",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with bresaola, arugula, and grated Parmesan",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Veneto",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "14.50",
    quantity: "30",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with cooked ham",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Prosciutto",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "9.90",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Pizza with fresh mushrooms",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Pizza Funghi",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "9.90",
    quantity: "40",
  },
  {
    addedBy: "Ferris Osteria",
    description: "White pizza with olive oil and rosemary",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Focaccia Pina",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "5.50",
    quantity: "50",
  },
  {
    addedBy: "Ferris Osteria",
    description: "Italian bread with tomatoes and onions",
    email: "contact@ferrisosteria.com",
    foodCategory: "Pizza",
    foodName: "Bruschetta",
    img: "https://i.ibb.co/yF6nMctN/125812849-173921387742858-732706592254190672-n.jpg",
    origin: "Italy",
    price: "5.50",
    quantity: "50",
  },
];
